services:
  - type: web
    name: rstriana-api
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --production=false
    startCommand: node server/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: RESEND_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: TO_EMAIL
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://rstriana.com,https://rstriana.dev,https://www.rstriana.com

